# Redirects the poe trade api 
[[redirects]]
  from = "api/trade/data/stats"
  to = "https://www.pathofexile.com/api/trade/data/stats"
  status = 200
  force = true

[[redirects]]
  from = "api/trade/search/Kalandra"
  to = "https://www.pathofexile.com/api/trade/search/Kalandra"
  status = 200
  force = true
  